#!/bin/bash

pacman -Syu --noconfirm grub os-prober nano initramfs

#locale setup
echo "Select locale:"
read -p "Press enter to continue:"

#nano /etc/locale.gen
echo en_US.UTF-8 UTF-8 > /etc/locale.gen

localectl set-locale LANG=en_US.UTF-8
export LANG=en_US.UTF-8
locale-gen
locale -a

echo "Select your timezone:"
tzselect | read timeZone
ln -sf $timeZone /etc/localtime
hwclock --systohc --utc

echo "Configure repositories (multilib support):"
read -p "Press enter to continue:"
sed -i 's/#[multilib]/[multilib]/g' /etc/pacman.conf
sed -i 's/#Include/Include/g' /etc/pacman.conf
nano /etc/pacman.conf
pacman -Syu --noconfirm

clear

echo What should the hostname be?
read hostName
echo "$hostName" >> /etc/hostname
echo "127.0.1.1 localhost.localdomain $hostName" >> /etc/hosts

clear

echo "Create password for root:"
passwd

clear

echo "What should the user name be?"
read userName
useradd -m -g users -G wheel,storage,power -s /bin/bash $userName

clear

echo "Create password for $userName:"
passwd $userName
#Allow all users to use sudo if they know the password
echo "ALL ALL=(ALL) ALL" >> /etc/sudoers

#bootloader-gen
os-prober
##reorder autodetect and block hooks for universal hardware booting
sed -i 's/autodetect modconf block/block autodetect modconf/g' /etc/mkinitcpio.conf
mkinitcpio -p linux

UEFI="null"
while :
do
      echo "Is this a UEFI system? (yes, no)"
      read UEFI
      if [ "$UEFI" == "yes" ]
      then
            pacman -S --noconfirm efibootmgr
            #/boot/efi already made
            grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi
            break
      elif [ "$UEFI" == "no" ]
      then
            echo "Where should grub be installed? (sda, sdb)"
            read iGrub
            grub-install --target=i386-pc --recheck /dev/$iGrub
            break
      fi
done

echo -e "\n\nGRUB_DEFAULT=saved" >> /etc/default/grub
echo "GRUB_SAVEDEFAULT=true" >> /etc/default/grub
echo "GRUB_FORCE_HIDDEN_MENU=TRUE" >> /etc/default/grub

grub-mkconfig -o /boot/grub/grub.cfg

if [ "$UEFI" == "yes" ]
then
      mkdir /boot/efi/EFI/BOOT
      cp /boot/efi/EFI/GRUB/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI
      echo "bcf boot add 1 fs0:\EFI\GRUB\grubx64.efi \"Arch GRUB bootloader\"\nexit" >> /boot/efi/startup.nsh
fi

clear

#aur helper
echo "Installing trizen:"
echo EDITOR="/usr/bin/nano" >> /etc/environment

cd /home/$userName
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/trizen.tar.gz
tar -xvzf trizen.tar.gz
cd /home/$userName/trizen

chown -hR $userName /home/$userName

sudo -u $userName makepkg -csri --skippgpcheck

clear

#intel ucode
echo "Install if using Intel processor:"
pacman -S intel-ucode

clear

echo "Which desktop environment would you like to use? (plasma, gnome3, xfce, or none)"
read deWM
case $deWM in
      plasma)
           pacman -S --noconfirm plasma-meta plasma-nm spectacle konsole gwenview dolphin partitionmanager kate ark qbittorrent
           systemctl enable sddm.service ;;
      gnome3)
           pacman -S --noconfirm gnome gparted gedit file-roller deluge
           systemctl enable gdm.service ;;
      xfce)
           pacman -S --noconfirm xfce4 xfce4-goodies gparted file-roller deluge sddm network-manager-applet gvfs pavucontrol
           systemctl enable sddm.service ;;
      none)
           ;;
esac

pacman -Syu --noconfirm linux-headers networkmanager bash-completion wpa_supplicant xorg-xinit xf86-video-vesa xorg-apps xorg firefox alsa-utils pulseaudio pulseaudio-bluetooth pulseaudio-alsa p7zip htop wine-staging winetricks libreoffice-fresh mpv adwaita-icon-theme links ntfs-3g



sysctl -w net.ipv4.ip_default_ttl=128
systemctl enable NetworkManager
systemctl enable wpa_supplicant
systemctl enable bluetooth.service

rm -rf /ainstall /aconfig /home/$userName/trizen*

clear

echo "Install Nvidia GPU drivers with package nvidia (400+), nvidia-340xx (8000-300), or nvidia-304xx (6000-7000)"
echo "You'll also probably want nvidia-settings and lib32-nvidia-utils for configuration and games."
echo "You may need to modprobe your wifi driver to get it running at first."
