#!/bin/bash

############## INSIDE ARCH INSTALL ##############

echo "Select locale:"
echo "Press enter to continue:"
nano /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8
ls -s /usr/share/zoneinfo/America/New_York > /etc/localtime
hwclock --systohc --utc

echo "Configure repositories (multilib support):"
echo "Press enter to continue:"
read -p
nano /etc/pacman.conf

echo What should the hostname be?
read hostName
echo "$hostName" >> /etc/hostname

echo "Install iw and wpa_supplicant if device needs wifi."
pacman -Sy iw wpa_supplicant

echo "Create password for root:"
passwd

echo "What should the user name be?:"
read userName
useradd -m -g users -G wheel,storage,power -s /bin/bash $userName

echo "Create password for $userName:"
passwd $userName
#Allow all users to use sudo
echo "ALL ALL=(ALL) ALL" >> /etc/sudoers

#bootloader-gen
pacman -Sy grub os-prober
mkinitcpio -p linux
grub-install --target=i386-pc --recheck /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

#pacaur
echo "Installing pacaur:"
gpg --recv-keys --keyserver hkp://pgp.mit.edu
echo "EDITOR="/usr/bin/nano"" >> /etc/environment

cd /home/$userName
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/cower.tar.gz
tar -xvzf cower.tar.gz
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/pacaur.tar.gz
tar -xvzf pacaur.tar.gz
cd /home/$userName/cower

chown -hR $userName /home/$userName

sudo -u $userName makepkg -csri --skippgpcheck
cd /home/$userName/pacaur
sudo -u $userName makepkg -csri --skippgpcheck

#intel ucode
echo "Install if using Intel processor:"
pacman -Sy intel-ucode

clear
#networking
ip addr
echo "Enter the name of your network device"
read $netDevice
systemctl enable dhcpcd@$netDevice
systemctl start dhcpcd@$netDevice

echo "Installing KDE plasma and programs:"
echo "Install GPU drivers with package nvidia (400+), nvidia-340xx (8000-300), or nvidia-304xx (6000-7000)"
echo "Press enter to continue:"
read -p
pacman -S plasma-meta bash-completion xorg-xinit xf86-video-vesa xorg-apps xorg firefox pulseaudio libreoffice-fresh spectacle konsole gwenview dolphin ark p7zip htop wine-staging partitionmanager kate qbittorrent baka-mplayer
systemctl enable sddm.service
clear

echo "Install GPU drivers with package nvidia (400+), nvidia-340xx (8000-300), or nvidia-304xx (6000-7000)"
