#!/bin/bash

#ARCHLINUX INSTALL SCRIPTS MODE

ping archlinux.org -c 4

pacman -Sy

loadkeys "us"

timedatectl set-ntp true

lsblk

echo enter which drive to format as ext4 (ex: sda ,sdb, or sdc):
read drivePath
sleep 1s

mkfs.ext4 /dev/$drivePath

echo Mounting $drivePath
mount $drivePath /mnt

echo Installing base and base-devel
sleep 1s

pacstrap /mnt base base-devel

echo Generating fstab
genfstab -U /mnt >> /mnt/etc/fstab

echo Chrooting into installation
echo Run aconfig inside the chroot environment to finish installation

mv ainstall /mnt
mv aconfig /mnt
sleep 1s

arch-chroot /mnt
